spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: micro_user_route
          uri: lb://user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: micro_goods_route
          uri: lb://goods
          predicates:
            - Path=/api/brand/**
          filters:
            - StripPrefix=1
              #- StripPrefix=1
              #用户微服务
        #- id: changgou_user_route
        #  uri: lb://user
        #  predicates:
        #    - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
        #  filters:
        #    - StripPrefix=1
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true